services:
  php:
    image: akeneo/pim-php-dev:8.1
    environment:
      COMPOSER_HOME: /var/www/.composer
      PHP_IDE_CONFIG: serverName=pim-family-templates
      XDEBUG_CONFIG: client_host=172.17.0.1
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    volumes:
      - ./:/srv/pim-family-templates
      - ${HOST_COMPOSER_HOME:-~/.composer}:/var/www/.composer
    working_dir: /srv/pim-family-templates
    command: php
    user: www-data

  php-gcloud:
    image: akeneo/pim-php-dev-gcloud:8.1
    build: .
    environment:
      COMPOSER_HOME: /var/www/.composer
      PHP_IDE_CONFIG: serverName=pim-family-templates
      XDEBUG_CONFIG: client_host=172.17.0.1
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    volumes:
      - ./:/srv/pim-family-templates
      - ${HOST_GCLOUD_CONFIG:-~/.config/gcloud}:/var/www/.config/gcloud
    working_dir: /srv/pim-family-templates
    command: php
    user: www-data

  node:
    image: akeneo/node:18
    environment:
      YARN_CACHE_FOLDER: /home/node/.yarn
    volumes:
      - ./:/srv/pim-family-templates
      - ${HOST_YARN_CACHE_FOLDER:-~/.cache/yarn}:/home/node/.yarn
    working_dir: /srv/pim-family-templates
