version: 2.1

orbs:
  slack: circleci/slack@3.4.2

machine: &machine
  machine:
    image: ubuntu-2204:current

slack-fail-post-step: &slack-fail-post-step
  post-steps:
    - slack/status:
        channel: raccoons-alerting
        webhook: $SLACK_KER_FAMILH_WEBHOOK
        fail_only: true

slack-post-step: &slack-post-step
  post-steps:
    - slack/status:
        channel: raccoons-alerting
        webhook: $SLACK_KER_FAMILH_WEBHOOK
        fail_only: false

parameters:
  trigger:
    default: ""
    type: string

jobs:
  install:
    <<: *machine
    steps:
      - checkout
      - run:
          name: Set up file permissions
          command: mkdir -p ~/.composer ~/.cache/yarn && sudo chown -R 1000:1000 ../project ~/.cache ~/.composer
      - run:
          name: Install dependencies
          command: make install
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  test_generator:
    <<: *machine
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Set up file permissions
          command: sudo chown -R 1000:1000 ../project
      - run:
          name: Run static analysis
          command: make static
      - run:
          name: Run cs analysis
          command: make cs
      - run:
          name: Run tests
          command: make tests

  lint_templates:
    <<: *machine
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Set up file permissions
          command: mkdir -p ~/.cache/yarn && sudo chown -R 1000:1000 ../project ~/.cache
      - run:
          name: Run lint templates
          command: make lint-templates

  minify_templates:
    <<: *machine
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Set up file permissions
          command: sudo chown -R 1000:1000 ../project
      - run:
          name: Minify templates
          command: make minify-templates
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  save_usages:
    <<: *machine
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Set up file permissions
          command: sudo chown -R 1000:1000 ../project
      - run:
          name: Save usages
          command: CI=true make save-usages

  commit_and_push:
    <<: *machine
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys:
          fingerprints:
            - 97:a4:35:1c:49:e9:55:8f:ec:77:e2:e0:1c:2d:75:a7
      - run:
          name: Set up git
          command: |
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_97a4351c49e9558fec77e2e01c2d75a7 -o UserKnownHostsFile=~/.ssh/known_hosts -o IdentitiesOnly=Yes'
            git config --global user.email "family-templates@akeneo.com"
            git config --global --add safe.directory $PWD
      - run:
          name: Commit and push changes
          command: |
            git diff --quiet && git diff --staged --quiet || git commit -am "Update minified templates"
            git push --set-upstream origin HEAD

  go_to_merguez:
    docker:
      - image: alpine
    steps:
      - run:
          name: Go to merguez
          command: echo "CI is green! Let's merguez!"

workflows:
  pull_request:
    jobs:
      - ready_to_test?:
          type: approval
          filters:
            branches:
              ignore:
                - main
      - install:
          requires:
            - ready_to_test?
      - test_generator:
          requires:
            - install
      - lint_templates:
          requires:
            - install
      - go_to_merguez:
          requires:
            - test_generator
            - lint_templates

  minify_templates:
    jobs:
      - install:
          filters:
            branches:
              only: main
      - lint_templates:
          requires:
            - install
      - minify_templates:
          requires:
            - lint_templates
      - commit_and_push:
          requires:
            - minify_templates

  save_usages:
    when:
      or:
        - and:
            - equal: [scheduled_pipeline, << pipeline.trigger_source >>]
            - equal: [save_usages, << pipeline.schedule.name >>]
        - equal: [save_usages, << pipeline.parameters.trigger >>]
    jobs:
      - install:
          <<: *slack-fail-post-step
      - save_usages:
          <<: *slack-post-step
          requires:
            - install
